apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMUG51UWZEYXJlQzdwYTlMVWZqCiszanlwQXJsTUNMa1lFQjlrdURnT3B1YUdESUxGSkxZTml5UnE0MFVCK0J6QlJXVlFTR2ZXQmozaDhJdEZvRmMKOVp4MzZQZXJkZDZQVksrMjBYL1d2dFcrMTBmQXZEVW81bFRJeHNNcjNxR2xmWTgydDRwSlV0RjQ3Z2RwK2Q2VApOMFJKYXBtakhjMmpib0lUMXA2RUJJVml0cGhENk0rUlVPZVVDdm1DanBHRTg3RkYwdEpMY0lnT3JpUXZPeG5jCnVvZ1JsOFk4NHF4L04wVzdDYXJ3ZmJ3MW5XZERWaXl1VlIrallkUlhLNExBY2cyVXlNT3RtdWZyZ2JmUCt4TkwKcWtrZmowL3JhMER0eFd6blRHWVB2OWxORWtIT1A3aUVQUitVZ2FLTUdNUytHZjErMnQyZHc3Q3RNdDloN0pJTwpCWnNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJMWUs3bGs0SUZjMnU0dmNzd24ybmd6ZnYrClY1UG44QlAwQlpHNzFGZ1MyNElDRlpQZ3pIWXF0OE1KTUdGdHFybVQyNTJPV3RiMGsrbm1qTmFsTlQ3bGc0YWoKOStodDZOdTB4dS83TEFsM0lFTTRPaU9PZmpFamtQVzh5bDBZbzhNZ2UwQSszaXNveEhnWngwTnJYekZvTkV5cAprN0Eva3U3dC81VHBlZlFOS0g1K2wvallmM09TRUxMV0IvUlBmZUlJTWhueENhNTZUWldsT2dER0pWZnR4aVA0CnRkZjFmS0xxSnEvZWNZcTFEOENlVm4vYTRYQUdMUVQ1TXpxQnBDU3Znc3FLckIwV3A0M3dNVDdlUEIrdHZHbWgKQVlvZm1YYWFWUnF0QVJHbjJ2VHNmTGVDQ1h1Wkd1VGVRTTVnU3Bsb3RyUEFPYXh2eGE3T1I4QkNSVGsvCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=ry
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth